import { DashboardProvider } from "~/app/_components/dashboardProvider";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section>
      <main>
        <DashboardProvider>{children}</DashboardProvider>
      </main>
    </section>
  );
}
